INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Gregory Alan Isakov');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Adele');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('The Lumineers');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Morningsiders');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Billy Joel');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('4 non Blondes');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Joy Olandokun');
INSERT INTO APP.A_ARTIST (A_NAME) VALUES ('Hozier');
